version: "3.9"

services:
  mariadb:
    image: mariadb:12
    container_name: financeapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financeapp
      MYSQL_USER: financeuser
      MYSQL_PASSWORD: financepass
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
